### ISSUE TITLE
macos compatibility?

### ISSUE THREAD

**Issue by lin-ycv** [mcneel/GhCanvasViewport#12]
just wondering if it's possible to achieve mac compatibility?

**Comment by sbaer** [comment]
Maybe some day. We are definitely not there yet with respect to how the core of Rhino is structured.

**Comment by lin-ycv** [comment]
Then is there an alternative to achieve something similar on Mac?
At least the ability to view an active viewport in a Panel?

**Comment by sbaer** [comment]
No current alternative. This is being prototyped in Rhino 8 with a different type of panel, but this will need to wait until we have the details ironed out with the prototype.
